# Generated by Django 6.0.2 on 2026-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
